global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:3001']
    metrics_path: /metrics

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:3002']
    metrics_path: /metrics

  - job_name: 'inventory-service'
    static_configs:
      - targets: ['inventory-service:3003']
    metrics_path: /metrics

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:3004']
    metrics_path: /metrics
